Make jackbone work with paths with spaces

diff --git a/jackbone b/jackbone
--- a/jackbone
+++ b/jackbone
@@ -1,13 +1,19 @@
 #!/bin/bash
-#
 
-command=$1
-target=$2
+command="$1"
+target="$2"
+
+export PROJECT_PATH="`pwd`"
+export EFILE="$PROJECT_PATH/build/tmp/jackbone.out"
+cd `dirname "$0"`
+export JACKBONEGAP_PATH="`pwd`"
 
 function error() {
-    test -e $EFILE && cat $EFILE
+    test -e "$EFILE" && cat "$EFILE"
     echo
     echo "[ERROR] $1"
+    test "x$2" != "x" && echo "        $2"
+    test "x$3" != "x" && echo "        $3"
     echo
     exit  1
 }
@@ -49,36 +55,27 @@ function usage {
 }
 
 function checkNeededFiles() {
-    test -e $PROJECT_PATH/config || error "config file is missing, create one from config-sample."
-    test -e $PROJECT_PATH/assets/Default.png || error "assets/Default.png is missing (should be a 2048x2048 image)."
-    test -e $PROJECT_PATH/assets/Icon.png || error "assets/Icon.png is missing (should be a 2048x2048 image)."
-    n=`ls -1 $PROJECT_PATH/app/html/ | wc -l`
+    test -e "$PROJECT_PATH/config" || error "config file is missing, create one from config-sample."
+    test -e "$PROJECT_PATH/assets/Default.png" || error "assets/Default.png is missing (should be a 2048x2048 image)."
+    test -e "$PROJECT_PATH/assets/Icon.png" || error "assets/Icon.png is missing (should be a 2048x2048 image)."
+    n=`ls -1 "$PROJECT_PATH/app/html/" | wc -l`
     [ $n -gt 0 ] || error "Please add your handlebars templates into app/html (at least one is needed)"
-
-#    if [ "x$target" = "xios" ]; then
-#        test -e $PROJECT_PATH/ios/Info.plist
-#    fi
 }
 
-export PROJECT_PATH="`pwd`"
-cd `dirname $0`
-export JACKBONEGAP_PATH="`pwd`"
-
 script="scripts/$command.sh"
-test -e $script || usage
+test -e "$script" || usage
 
 export DOWNLOADS_PATH="$PROJECT_PATH/.downloads"
 export LIBS_PATH="$PROJECT_PATH/libs"
 export JS_LIBS_PATH="$PROJECT_PATH/app/js/libs"
-export EFILE="$PROJECT_PATH/build/tmp/jackbone.out"
 
-if [ x$command != xboilerplate ]; then
+if [ "x$command" != xboilerplate ]; then
     checkNeededFiles
-    . $PROJECT_PATH/config
+    . "$PROJECT_PATH/config"
 
     if [ "x$PROJECT_NAME" = "x" ]; then
         error "config file should specify a project name."
     fi
 fi
 
-. $script $@ || exit 1
+. "$script" $@ || exit 1
